name: Test Package
on:
  workflow_dispatch:

jobs:
  packager:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bigwigs packager
        uses: BigWigsMods/packager@7cd7fe5fede4ca80f63742e6bc1d777914814380
        with:
          args: "-d -o -u -m .pkgmeta -S"
      - name: Get name of zip file
        run: echo "artifact=`readlink -f .release/*.zip`" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: CoreLootManager
          path: ${{ env.artifact }}